require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7.2

Layout/LineLength:
  Max: 120

Naming/VariableNumber:
  Exclude:
    - 'spec/**/*'

MultipleMemoizedHelpers:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Enabled: false

Documentation:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'layout/**/*'
    - 'db/migrate/**/*'
    - 'db/seeds.rb'
    - 'db/schema.rb'
    - 'bin/bundle'
    - 'config/**/*'

RSpec/NamedSubject:
  Exclude:
    - 'spec/controllers/books_controller_spec.rb'

Rails/FilePath:
  Exclude:
    - 'spec/rails_helper.rb'

RSpec/DescribedClass:
  Exclude:
    - 'spec/models/address_spec.rb'
    - 'spec/models/review_spec.rb'
    - 'spec/models/book_image_spec.rb'

RSpec/NamedSubject:
  Exclude:
    - 'spec/controllers/books_controller_spec.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/features/settings/settings_spec.rb'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/features/settings/settings_spec.rb'
    - 'spec/features/carts/cart_page_spec.rb'
    - 'spec/features/carts/cart_page_js_spec.rb'
    - 'spec/features/checkout/quick_registrate_page_spec.rb'

Style/SymbolProc:
  Exclude:
    - 'app/admin/book_images.rb'

RSpec/LetSetup:
  Exclude:
    - 'spec/controllers/carts_controller_spec.rb'
    - 'spec/features/carts/cart_page_js_spec.rb'
    - 'spec/features/checkout/quick_registrate_page_spec.rb'
