executors:
  ruby:
    docker:
      - image: 'circleci/ruby:2.7.0-node-browsers'
  ruby_with_db:
    docker:
      - image: 'circleci/ruby:2.7.0-node-browsers'
      - image: 'circleci/postgres:12.1-alpine-ram'
    environment:
      DATABASE_URL: 'postgres://postgres:postgres@127.0.0.1:5432'
orbs:
  rails: medpeer/rails@1.2.0
version: 2.1
workflows:
  rspec:
    jobs:
      - rails/rb-deps:
          executor: ruby
      - rails/js-deps:
          executor: ruby
      - rails/assets:
          executor: ruby
          requires:
            - rails/rb-deps
            - rails/js-deps
      - rails/rspec:
          db-port: '5432'
          executor: ruby_with_db
          parallelism: 4
          requires:
            - rails/assets