version: 2.1
orbs:
  ruby: circleci/ruby@1.8.0
jobs:
  rspec-test:
    docker:
      - image: cimg/ruby:2.7.2
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Run RSpec tests
          command: bundle exec rspec
workflows:
    build:
        jobs:
            - rspec-test